/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TypeIndexLazyImport = createFileRoute('/type/')()
const StudentsIndexLazyImport = createFileRoute('/students/')()
const ManufactureIndexLazyImport = createFileRoute('/manufacture/')()
const TypeCreateLazyImport = createFileRoute('/type/create')()
const TypeIdLazyImport = createFileRoute('/type/$id')()
const StudentsCreateLazyImport = createFileRoute('/students/create')()
const StudentsIdLazyImport = createFileRoute('/students/$id')()
const ManufactureCreateLazyImport = createFileRoute('/manufacture/create')()
const ManufactureIdLazyImport = createFileRoute('/manufacture/$id')()
const TypeEditIdLazyImport = createFileRoute('/type/edit/$id')()
const StudentsEditIdLazyImport = createFileRoute('/students/edit/$id')()
const ManufactureEditIdLazyImport = createFileRoute('/manufacture/edit/$id')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TypeIndexLazyRoute = TypeIndexLazyImport.update({
  id: '/type/',
  path: '/type/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/index.lazy').then((d) => d.Route))

const StudentsIndexLazyRoute = StudentsIndexLazyImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/students/index.lazy').then((d) => d.Route),
)

const ManufactureIndexLazyRoute = ManufactureIndexLazyImport.update({
  id: '/manufacture/',
  path: '/manufacture/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/index.lazy').then((d) => d.Route),
)

const TypeCreateLazyRoute = TypeCreateLazyImport.update({
  id: '/type/create',
  path: '/type/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/create.lazy').then((d) => d.Route))

const TypeIdLazyRoute = TypeIdLazyImport.update({
  id: '/type/$id',
  path: '/type/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/$id.lazy').then((d) => d.Route))

const StudentsCreateLazyRoute = StudentsCreateLazyImport.update({
  id: '/students/create',
  path: '/students/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/students/create.lazy').then((d) => d.Route),
)

const StudentsIdLazyRoute = StudentsIdLazyImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/students/$id.lazy').then((d) => d.Route))

const ManufactureCreateLazyRoute = ManufactureCreateLazyImport.update({
  id: '/manufacture/create',
  path: '/manufacture/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/create.lazy').then((d) => d.Route),
)

const ManufactureIdLazyRoute = ManufactureIdLazyImport.update({
  id: '/manufacture/$id',
  path: '/manufacture/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/$id.lazy').then((d) => d.Route),
)

const TypeEditIdLazyRoute = TypeEditIdLazyImport.update({
  id: '/type/edit/$id',
  path: '/type/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/edit/$id.lazy').then((d) => d.Route))

const StudentsEditIdLazyRoute = StudentsEditIdLazyImport.update({
  id: '/students/edit/$id',
  path: '/students/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/students/edit/$id.lazy').then((d) => d.Route),
)

const ManufactureEditIdLazyRoute = ManufactureEditIdLazyImport.update({
  id: '/manufacture/edit/$id',
  path: '/manufacture/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/$id': {
      id: '/manufacture/$id'
      path: '/manufacture/$id'
      fullPath: '/manufacture/$id'
      preLoaderRoute: typeof ManufactureIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/create': {
      id: '/manufacture/create'
      path: '/manufacture/create'
      fullPath: '/manufacture/create'
      preLoaderRoute: typeof ManufactureCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/create': {
      id: '/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof StudentsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/$id': {
      id: '/type/$id'
      path: '/type/$id'
      fullPath: '/type/$id'
      preLoaderRoute: typeof TypeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/create': {
      id: '/type/create'
      path: '/type/create'
      fullPath: '/type/create'
      preLoaderRoute: typeof TypeCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/': {
      id: '/manufacture/'
      path: '/manufacture'
      fullPath: '/manufacture'
      preLoaderRoute: typeof ManufactureIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/': {
      id: '/type/'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof TypeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/edit/$id': {
      id: '/manufacture/edit/$id'
      path: '/manufacture/edit/$id'
      fullPath: '/manufacture/edit/$id'
      preLoaderRoute: typeof ManufactureEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/edit/$id': {
      id: '/students/edit/$id'
      path: '/students/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof StudentsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/edit/$id': {
      id: '/type/edit/$id'
      path: '/type/edit/$id'
      fullPath: '/type/edit/$id'
      preLoaderRoute: typeof TypeEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/manufacture': typeof ManufactureIndexLazyRoute
  '/students': typeof StudentsIndexLazyRoute
  '/type': typeof TypeIndexLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/manufacture': typeof ManufactureIndexLazyRoute
  '/students': typeof StudentsIndexLazyRoute
  '/type': typeof TypeIndexLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/manufacture/': typeof ManufactureIndexLazyRoute
  '/students/': typeof StudentsIndexLazyRoute
  '/type/': typeof TypeIndexLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/students/$id'
    | '/students/create'
    | '/type/$id'
    | '/type/create'
    | '/manufacture'
    | '/students'
    | '/type'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
    | '/type/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/students/$id'
    | '/students/create'
    | '/type/$id'
    | '/type/create'
    | '/manufacture'
    | '/students'
    | '/type'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
    | '/type/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/students/$id'
    | '/students/create'
    | '/type/$id'
    | '/type/create'
    | '/manufacture/'
    | '/students/'
    | '/type/'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
    | '/type/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  ManufactureIdLazyRoute: typeof ManufactureIdLazyRoute
  ManufactureCreateLazyRoute: typeof ManufactureCreateLazyRoute
  StudentsIdLazyRoute: typeof StudentsIdLazyRoute
  StudentsCreateLazyRoute: typeof StudentsCreateLazyRoute
  TypeIdLazyRoute: typeof TypeIdLazyRoute
  TypeCreateLazyRoute: typeof TypeCreateLazyRoute
  ManufactureIndexLazyRoute: typeof ManufactureIndexLazyRoute
  StudentsIndexLazyRoute: typeof StudentsIndexLazyRoute
  TypeIndexLazyRoute: typeof TypeIndexLazyRoute
  ManufactureEditIdLazyRoute: typeof ManufactureEditIdLazyRoute
  StudentsEditIdLazyRoute: typeof StudentsEditIdLazyRoute
  TypeEditIdLazyRoute: typeof TypeEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  ManufactureIdLazyRoute: ManufactureIdLazyRoute,
  ManufactureCreateLazyRoute: ManufactureCreateLazyRoute,
  StudentsIdLazyRoute: StudentsIdLazyRoute,
  StudentsCreateLazyRoute: StudentsCreateLazyRoute,
  TypeIdLazyRoute: TypeIdLazyRoute,
  TypeCreateLazyRoute: TypeCreateLazyRoute,
  ManufactureIndexLazyRoute: ManufactureIndexLazyRoute,
  StudentsIndexLazyRoute: StudentsIndexLazyRoute,
  TypeIndexLazyRoute: TypeIndexLazyRoute,
  ManufactureEditIdLazyRoute: ManufactureEditIdLazyRoute,
  StudentsEditIdLazyRoute: StudentsEditIdLazyRoute,
  TypeEditIdLazyRoute: TypeEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/manufacture/$id",
        "/manufacture/create",
        "/students/$id",
        "/students/create",
        "/type/$id",
        "/type/create",
        "/manufacture/",
        "/students/",
        "/type/",
        "/manufacture/edit/$id",
        "/students/edit/$id",
        "/type/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/manufacture/$id": {
      "filePath": "manufacture/$id.lazy.jsx"
    },
    "/manufacture/create": {
      "filePath": "manufacture/create.lazy.jsx"
    },
    "/students/$id": {
      "filePath": "students/$id.lazy.jsx"
    },
    "/students/create": {
      "filePath": "students/create.lazy.jsx"
    },
    "/type/$id": {
      "filePath": "type/$id.lazy.jsx"
    },
    "/type/create": {
      "filePath": "type/create.lazy.jsx"
    },
    "/manufacture/": {
      "filePath": "manufacture/index.lazy.jsx"
    },
    "/students/": {
      "filePath": "students/index.lazy.jsx"
    },
    "/type/": {
      "filePath": "type/index.lazy.jsx"
    },
    "/manufacture/edit/$id": {
      "filePath": "manufacture/edit/$id.lazy.jsx"
    },
    "/students/edit/$id": {
      "filePath": "students/edit/$id.lazy.jsx"
    },
    "/type/edit/$id": {
      "filePath": "type/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
